---
- name: Extract ctlplane IP addresses and run command on servers
  hosts: all
  gather_facts: yes
  become: yes
  remote_user: ec2-user #change this to the remote user
  tasks:
    - name: Run command on servers and save output locally
      ansible.builtin.shell: "date"
      register: command_output
      run_once: yes

    - name: Debug command output
      ansible.builtin.debug:
        msg: "{{ command_output.stdout }}"

    - name: Create your local file on master node
      ansible.builtin.file:
        path: "report.txt"
        state: touch
        mode: '0644'
      delegate_to: localhost
      become: no

    - name: Create report.txt file or append to existing file
      ansible.builtin.lineinfile:
        path: "report.txt"
        line: "{{ item }} - {{ command_output.stdout }}"
      loop: "{{ ansible_play_batch }}"
      delegate_to: localhost
      become: no